### ISSUE TITLE
Gradle spigot dependency

### ISSUE THREAD

**Issue by RoboMWM** [Di3mex/ExtraHardMode#34]
So it looks like you try to build spigot via buildtools.jar with gradle... I don't use gradle myself but this plugin does, perhaps you can see how it sets its dependencies: https://github.com/iSach/UltraCosmetics

I'd rather stick with maven though, not sure why you switched :/

In the meantime, I just re-added the pom to my fork c:

**Comment by Di3mex** [comment]
I switched because I'm used to gradle from android development and I tried to do all the buildtools and stuff with gradle. The cool thing about this is is that the buildEHM task builds the jar and copies it straight to a local server folder. Before I always had to copy it myself. I thought of maybe readding the pom.xml for people still wanting to use maven for dependencies.

**Comment by RoboMWM** [comment]
Lol I've heard that people hate gradle if they were introduced to it via android. And I'd rather dev for Windows Phone :P

Anyways that's what I've done - I use a script that auto-builds and moves to my plugins/updates and have no need of using buildtools and whatnot (you may have had trouble with spigot's repo which the path has changed).

I also strangely had an issue of the maven plugin zipping itself or something in later builds so I just commented it out.

Since I have no need of rebuilding the jar I definitely prefer using maven and would suggest keeping a pom in there especially if you intend to keep depending on spigot/bukkit via buildtools instead of the maven repo.
